adjacencyList = {'Gdansk': ['Szczecin', 'Warszawa'],
                 'Szczecin': ['Gdansk', 'Poznan'],
                 'Bialystok': ['Warszawa'],
                 'Poznan': ['Szczecin', 'Warszawa', 'Lodz', 'Wroclaw'],
                 'Warszawa': ['Bialystok', 'Gdansk', 'Lublin', 'Kielce', 'Krakow', 'Katowice', 'Lodz', 'Poznan'],
                 'Lodz': ['Warszawa', 'Poznan', 'Krakow', 'Czestochowa'],
                 'Czestochowa': ['Lodz', 'Krakow', 'Katowice', 'Opole'],
                 'Kielce': ['Warszawa', 'Krakow'],
                 'Lublin': ['Warszawa', 'Rzeszow'],
                 'Wroclaw': ['Poznan', 'Opole'],
                 'Opole': ['Wroclaw', 'Katowice', 'Czestochowa'],
                 'Katowice': ['Opole', 'Czestochowa', 'Bielsko-biala', 'Warszawa', 'Krakow'],
                 'Krakow': ['Katowice', 'Czestochowa', 'Lodz', 'Warszawa', 'Kielce', 'Tarnow', 'Wieliczka', 'Skawina'],
                 'Tarnow': ['Krakow', 'Rzeszow'],
                 'Rzeszow': ['Tarnow', 'Lublin', 'Przemysl'],
                 'Bielsko-biala': ['Katowice', 'Wadowice'],
                 'Wadowice': ['Bielsko-biala', 'Skawina'],
                 'Skawina': ['Wadowice', 'Krakow'],
                 'Wieliczka': ['Krakow'],
                 'Przemysl': ['Rzeszow']}
